### PR TITLE
[useQuery] fixed refetching and added unit tests

### PR DESCRIPTION
**Pull request by teivienn**
- add unit tests for useQuery hook
- fix isLoading state when refresh request called

### CODE REVIEW

**Comment by teivienn** [comment]
Hi @debabin, I have a question about `aborted` status. It seems like a broken because when I created test this status every time was false.

Is it really broken or does it work but only in certain scenarios?

**Comment by debabin** [comment]
Hi @teivienn , thanks for working on our project. I need some time to look at the refetch and abort status. Thanks again.

**Comment by debabin** [comment]
Tell me why you think the behavior for loading needs to be changed? @teivienn

**Comment by teivienn** [comment]
> Tell me why you think the behavior for loading needs to be changed? @teivienn

Hi, Thank you for taking the time to respond.

First of all, I think we should stick to the behavior that tanstack-query has.
 
I have prepared a small [demo](https://stackblitz.com/edit/vitejs-vite-f3qqfvty?file=src%2FTanstack.jsx) to showing the loading states. Here's a comparison of the two hooks

I think the `isLoading`  should be responsible for the first load process. And the subsequent ones should remain false 

I don't know how clear this example will be. But let's say we have a component with lists and I would like to show the first loader when there is no data, and then when changing pages show only some indicator that loading is happening but still display data.
```tsx

import { useQuery } from '@siberiacancode/reactuse';

const [page, setPage] = useState(1)
const { data, isLoading, isRefetching } = useQuery(() => api(page), {
keys: [page]
})

if (isLoading) return <p>loading...</p>

/*
If I don't want to show the loader, I need to check the data 
if (isLoading && data.length === 0) return <p>loading...</p>
*/


return (
<div>
{data.map(() => ....)}
{isRefetching && <OverlayLoading />}

<button onClick={() => setPage(p => p+1)}>next</button>
</div>
)

```


Perhaps we should introduce another condition that will work like `isLoading` does now? Like `isFetching` fron tanstack-query

**Comment by teivienn** [comment]
Take a look at the latest changes, it may be more correct to clear the aborted status at the start of each new request. And I also added a new loading status that I wrote about above

**Comment by debabin** [comment]
After much thought about the interrupted status, I realized that perhaps it was not needed at all. I looked towards the tank and they don't have that. @teivienn Your idea with fetchinhg is very cool, this way the user will be able to separate different statuses in ui more easily

**Pull request merged**
